version: '3.8'

services:
  bawang:
    image: jzbdc/bawangnes:latest
    container_name: bawang-nes
    ports:
      - "8080:80"
    volumes:
      - ./roms:/usr/share/nginx/html/roms
    restart: unless-stopped
